import { TeacherType } from "@/models/teacher";

export const mockTeacherApplications: TeacherType[] = [
  {
    _id: "t1",
    name: "Alice Thompson",
    qualifications: ["Ph.D. in Mathematics", "M.Sc. in Statistics"],
    bio: "Passionate about making complex math simple and engaging for students.",
    yoe: 10,
    subjects: ["Mathematics", "Statistics"],
    hourlyRate: 50,
    averageRating: 4.8,
    availability: ["online", "both"],
    status: "pending",
  },
  {
    status: "pending",
    _id: "t2",
    name: "David Lee",
    qualifications: [
      "M.S. in Computer Science",
      "B.S. in Software Engineering",
    ],
    bio: "Experienced software engineer turned educator, focusing on practical coding skills.",
    yoe: 6,
    subjects: ["Computer Science", "Web Development"],
    hourlyRate: 40,
    averageRating: 4.6,
    availability: ["in-person", "both"],
  },
  {
    status: "pending",
    _id: "t3",
    name: "Sophia Martinez",
    qualifications: ["M.A. in Fine Arts", "B.A. in Art History"],
    bio: "Helping students explore their creative potential through traditional and digital mediums.",
    yoe: 5,
    subjects: ["Art", "Art History"],
    hourlyRate: 35,
    averageRating: 4.7,
    availability: ["online", "in-person"],
  },
  {
    status: "pending",
    _id: "t4",
    name: "James Rodriguez",
    qualifications: ["M.A. in History", "B.A. in Political Science"],
    bio: "Dedicated to making history come alive with engaging storytelling and analysis.",
    yoe: 8,
    subjects: ["History", "Political Science"],
    hourlyRate: 45,
    averageRating: 4.5,
    availability: ["both"],
  },
  {
    status: "pending",
    _id: "t5",
    name: "Emily Zhang",
    qualifications: ["M.F.A. in Creative Writing", "B.A. in Literature"],
    bio: "Empowering students to express themselves through storytelling and critical analysis.",
    yoe: 7,
    subjects: ["English Literature", "Creative Writing"],
    hourlyRate: 38,
    averageRating: 4.9,
    availability: ["online"],
  },
  {
    status: "pending",
    _id: "t6",
    name: "Robert Patel",
    qualifications: ["Ph.D. in Physics", "M.Sc. in Astronomy"],
    bio: "Bringing physics to life through experiments and real-world applications.",
    yoe: 12,
    subjects: ["Physics", "Astronomy"],
    hourlyRate: 55,
    averageRating: 4.8,
    availability: ["in-person"],
  },
  {
    status: "pending",
    _id: "t7",
    name: "Amara Okafor",
    qualifications: ["Ph.D. in Biological Sciences", "M.Sc. in Genetics"],
    bio: "Inspiring curiosity about the natural world through hands-on learning and research insights.",
    yoe: 9,
    subjects: ["Biology", "Genetics"],
    hourlyRate: 48,
    averageRating: 4.7,
    availability: ["both"],
  },
];
